### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink-workshop#19]
## ToDo

- [x] Fix sorting of players on scoreboard
- [x] Make scoreboard scrollable
- [x] Allow emoji's in player names
- [x] Add `*.lottie` animations
- [x] Remove numbers inside the cells (when the playing field is large they get unreadable)

**Comment by DoubleOTheven** [comment]
Emojis are fixed here: https://github.com/paritytech/ink-workshop/pull/25

**Comment by DoubleOTheven** [comment]
I can't reproduce the sorting of players. It seems to work right now. I will test again when we do a team game
